version: '3'

services:
  db:
    image: kartoza/postgis:12.0
    container_name: db
    restart: unless-stopped
    ports:
      - 7777:5432
    env_file: .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB 
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - backend-net

  backend:
    build:
      context: ./project/server/
    container_name: backend
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./project/server:/project/server
    depends_on:
      - db
    command: bash -c 'npm install; npm start;'
    networks:
      - backend-net
    env_file: .env
    environment:
      - DATABASE_URL=$DATABASE_URL
  
  frontend:
    build:
      context: ./project/client/
    container_name: frontend
    restart: unless-stopped
    ports:
      - 4200:4200
    volumes:
      - ./project/client:/project/client
    command: bash -c 'npm install; npm start;'
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge

volumes:
  pg_data: